sonar.projectKey=apds7311w-secure-payments
sonar.projectName=APDS7311w Secure Payments Portal
sonar.sources=api/src,web/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/data/**,**/certs/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
